# Generated by Django 5.1.6 on 2025-02-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/defaults/profile.png', null=True, upload_to=''),
        ),
    ]
