# Generated by Django 5.1.6 on 2025-02-20 22:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='static/defaults/profile.png', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
